name: Add or update Jira Issues with a FixVersion
description: This action will add the supplied list of FixVersions to the list of Jira Issue Keys
branding:
  icon: 'chevron-right'
  color: 'blue'
inputs:
  token:
    description: The github token used for authenticating to GitHub
    required: true
  fix_versions:
    description: A comma-separated list of FixVersions, if the FixVersion doesn't exist it will be created
    required: true
  issues:
    description: A comma-separated list of Jira issue keys
    required: true
  projects:
    description: >
      A comma separated list of project names to include in the results by, i.e. DEVOPS,PROJECT1
    required: false
  projects_ignore:
    description: >
      A comma separated list of project names to exclude from the results by, i.e. INTERNAL,PROJECT2
    required: false
  include_merge_messages:
    description: >
      When parsing commit messages, include merge and pull messages.
      This is disabled by default, to exclude tickets that may be included
      or fixed in other branches or pull requests.
    required: false
    default: 'false'
  jira_base_url:
    description: >
      The Jira cloud base url including protocol i.e. 'https://company.atlassian.net'
      or use environment variable JIRA_BASE_URL
    required: false
  jira_user_email:
    description: >
      The Jira cloud user email address
      or use environment variable JIRA_USER_EMAIL
    required: false
  jira_api_token:
    description: >
      The Jira cloud user api token
      or use environment variable JIRA_API_TOKEN
    required: false
  fail_on_error:
    description: If there is an error during transition, the action will error out.
    default: 'false'
    required: false

runs:
  using: 'node12'
  main: './dist/index.js'
